// File generated by FlutterFire CLI.
// IMPORTANT: Replace these values with the ones from your Firebase console
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Use Android config for Windows during development
        return android;
      case TargetPlatform.linux:
        // Use Android config for Linux during development
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv4SZWygSd_PHkfFK6DfO0YWS_nTJyx5o',
    appId: '1:585912533994:android:065084d50d692eed76a893',
    messagingSenderId: '585912533994',
    projectId: 'sleep-prediction-e251b',
    storageBucket: 'sleep-prediction-e251b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4SZWygSd_PHkfFK6DfO0YWS_nTJyx5o',
    appId: '1:585912533994:ios:065084d50d692eed76a893',
    messagingSenderId: '585912533994',
    projectId: 'sleep-prediction-e251b',
    storageBucket: 'sleep-prediction-e251b.firebasestorage.app',
    iosBundleId: 'com.sleepmodel.sleep-prediction',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4SZWygSd_PHkfFK6DfO0YWS_nTJyx5o',
    appId: '1:585912533994:web:065084d50d692eed76a893',
    messagingSenderId: '585912533994',
    projectId: 'sleep-prediction-e251b',
    authDomain: 'sleep-prediction-e251b.firebaseapp.com',
    storageBucket: 'sleep-prediction-e251b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4SZWygSd_PHkfFK6DfO0YWS_nTJyx5o',
    appId: '1:585912533994:macos:065084d50d692eed76a893',
    messagingSenderId: '585912533994',
    projectId: 'sleep-prediction-e251b',
    storageBucket: 'sleep-prediction-e251b.firebasestorage.app',
    iosBundleId: 'com.sleepmodel.sleep-prediction',
  );
} 